### ISSUE TITLE
Issue in downloading Book

### ISSUE THREAD

**Issue by MotiBaadror** [samj1912/Genesis#3]
when i click on download at the extension then this is happening . 
http://download.libgen.iohttp//libgen.io/get.php?md5=F6FE73A48B8B7AFF7205AB48D3905AA9&key=OGF22GR4IE29Y12O

**Comment by samj1912** [comment]
Which version of the extension are you using? I am able to download books just fine.

**Comment by MotiBaadror** [comment]
it was older . New one working fine .Thanks Bhaiya
